=== dmoellenbeck/mule4-usecases/ux-myid-api/src/main/resources/api/schemas/users-schema-input.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "properties": {
    "Allow Login": {
      "type": "number",
      "required": true
    },
    "Billing Center": {
      "type": "array",
      "required": true,
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "Business Title": {
      "type": "string",
      "required": false
    },
    "Business Unit": {
      "type": "string",
      "required": false
    },
    "City": {
      "type": "string",
      "required": false
    },
    "Company Code": {
      "type": "string",
      "required": false
    },
    "Company Name": {
      "type": "string",
      "required": false
    },
    "Country": {
      "type": "string",
      "required": false
    },
    "Email": {
      "type": "string",
      "required": true
    },
    "First Name": {
      "type": "string",
      "required": true
    },
    "Home Department": {
      "type": "string",
      "required": false
    },
    "Home Department Desc": {
      "type": "string",
      "required": false
    },
    "Is Active": {
      "type": "number",
      "required": true
    },
    "Last Name": {
      "type": "string",
      "required": true
    },
    "Manager ID": {
      "type": "string",
      "required": false
    },
    "Manager Name": {
      "type": "string",
      "required": false
    },
    "Mobile Number": {
      "type": "string",
      "required": false
    },
    "Network ID": {
      "type": "string",
      "required": true
    },
    "Routing Code": {
      "type": "array",
      "required": true,
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "TMS Roles": {
      "type": "array",
      "required": true,
      "items": {
        "type": "string"
      },
      "minItems": 0
    },
    "Start Date": {
      "type": "string",
      "required": false
    },
    "State": {
      "type": "string",
      "required": false
    },
    "Street": {
      "type": "string",
      "required": false
    },
    "Telephone Number": {
      "type": "string",
      "required": false
    },
    "Termination Date": {
      "type": "string",
      "required": false
    },
    "TimeZone": {
      "type": "string",
      "required": false
    },
    "Title": {
      "type": "string",
      "required": false
    },
    "User Name": {
      "type": "string",
      "required": true
    },
    "User Status": {
      "type": "string",
      "required": false
    },
    "User Type": {
      "type": "string",
      "required": true
    },
    "Zip Code": {
      "type": "string",
      "required": false
    }
  }
}

=== dmoellenbeck/mule4-usecases/ux-myid-api/src/test/resources/sample_data/json_2.json
{"Allow Login":1,"Billing Center":["NYC","CAL"],"Business Title":"Developer","Business Unit":"ABC","City":"Chesterbrook","Company Code":"ABC","Company Name":"AmerisourceBergen","Country":"USA","Email":"Suresh.Mukthapuram@amerisourcebergenDev.com","First Name":"Suresh","Home Department":"10110101","Home Department Desc":"IAM","Is Active":1,"Last Name":"Mukthapuram","Manager ID":"62115","Manager Name":"Kratz, Rick (A062115)","Mobile Number":"111-111-1919","Network ID":"A011209","Routing Code":["NYC","CAL"],"TMS Roles":["role1","role2"],"Start Date":"2017-05-18 00:00:00.0","State":"PA","Street":"1400","Telephone Number":"111-111-0999","Termination Date":"2017-05-31 00:00:00.0","TimeZone":"EST","Title":"Developer","User Name":"A011209","User Status":"Active","User Type":"Vendor","Zip Code":"19406"}
